[package]
name = "iv"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"
image = "0.24.7"
walkdir = "2.4.0"
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"